// 検索欄の下に出す検索の例。開くたびに、ふだんの言葉の例（talk）を多めに、
// カード名・決まった言い方の例（basic）を少し、ランダムに選んで並べる。
// どれも「読めない言葉が残らず、1枚以上当たる」ことをテストで確かめている（src/search/search.test.ts）

export const EXAMPLES_JA = {
  talk: [
    "エネ加速できる炎のカード",
    "ベンチに攻撃できる雷ポケモン",
    "にげるエネ0のたね",
    "相手の手札を減らすサポート",
    "コインで火力が上がるワザ",
    "水1個であとは無色のワザ",
    "トラッシュの枚数で変わる",
    "HP150以上の鋼ポケモン",
    "メガルカリオexデッキ",
    "ミライドンexと相性がいいカード",
    "大会でよく使われるサポート",
    "相手をねむりにするワザ",
    "どくにできるポケモン",
    "相手をまひさせるワザ",
    "やけどにするポケモン",
    "こんらんさせるワザ",
    "相手をどくとやけどにする",
    "ポケモンを回復できるグッズ",
    "ベンチのポケモンも回復できる",
    "回復できるワザ",
    "山札からたねポケモンを探す",
    "進化ポケモンを探す",
    "グッズを探す",
    "カードを引けるサポート",
    "カードを引ける特性",
    "カードを引けるワザ",
    "手札を山札に戻して引く",
    "手札を増やす",
    "相手のバトルポケモンを入れ替える",
    "自分のバトルポケモンと入れ替える",
    "逃げるエネを減らす",
    "にげる1以下のex",
    "ダメージを減らす特性",
    "ダメージを受けない特性",
    "次の番ダメージを受けないワザ",
    "相手のエネルギーをトラッシュする",
    "相手のサポートを妨害",
    "相手のグッズを封じる",
    "相手のワザを封じる",
    "相手の特性を消す",
    "相手を逃げられなくする",
    "相手の手札を見る",
    "ワンパンできるたねex",
    "2エネで100ダメージ以上",
    "3エネ以下無色技　水ポケモン",
    "雷エネ2個のワザ",
    "ワザのコストを減らす",
    "進化を早めるカード",
    "HPを増やすどうぐ",
    "ワザのダメージを上げるどうぐ",
    "炎ポケモンのダメージを上げる",
    "exにダメージを上げる",
    "弱点が炎の草ポケモン",
    "弱点がない",
    "超タイプのたねex",
    "悪タイプの2進化",
    "草タイプのex",
    "ベンチからでもダメージを与える特性",
    "自分にもダメージがあるワザ",
    "ダメカンをのせる",
    "トラッシュからエネをつける",
    "エネルギーゾーンからエネをつける",
    "自分のエネを移動する",
    "反撃できるポケモン",
    "手札が多いほど強いワザ",
    "ベンチの数で威力が上がる",
    "エネルギーが多いほど強いワザ",
    "ダメージを受けているほど強い",
    "相手がexなら強い",
    "160ダメージ以上のワザ",
    "コインを使うサポート",
    "状態異常を治す",
    "山札の上を見る",
    "手札をトラッシュする",
    "相手のポケモンを手札に戻す",
    "たねポケモンをベンチに出す",
    "大会でよく使われるグッズ",
    "大会でよく使われる雷ポケモン",
    "大会でよく使われるポケモン",
    "フシギバナexと相性がいいカード",
    "リザードンexと相性がいい",
    "ピカチュウexと相性がいい",
    "ミュウexと相性がいい",
    "ゲッコウガと相性がいい",
    "ダークライexデッキ",
    "メガチルタリスexデッキ",
    "ビークインexデッキ",
    "フーパexデッキ",
    "スイクンexデッキ",
    "ジバコイルデッキ",
    "メガアブソルexデッキ",
    "ルカリオデッキ",
    "ミロカロスexデッキ",
    "ピカチュウexデッキ",
    "ナッシーexデッキ",
    "フシギバナexデッキ",
    "サーナイトのデッキ",
    "カイリューと相性がいい",
    "ピカチュウexと組みたいカード",
    "博士の研究と相性がいい",
    "毎ターン使える特性",
    "回復しながら攻撃",
    "HPが高いたね",
    "2進化のサポート",
    "山札から進化",
    "入れ替えできるグッズ",
    "ダメージを受けると反撃",
    "ワザを使うと次のターン動けなくなる",
    "反動がある技",
    "相手を動けなくする",
  ],
  basic: [
    "アグロ",
    "ex",
    "メガシンカex",
    "ウルトラビースト",
    "ロケット団のカード",
    "古代のポケモン",
    "未来のポケモン",
    "ポケモンのどうぐ",
    "スタジアム",
    "化石",
    "ドラゴンタイプのポケモン",
    "ベンチ狙撃",
    "全体攻撃",
    "エネ破壊",
    "手札干渉",
    "ドロー",
    "サーチ",
    "回復",
    "エネ加速",
    "進化補助",
    "入れ替え",
    "エネ移動",
    "HP200以上",
    "ピカチュウ",
    "リザードン",
    "ミュウツーex",
    "ゲッコウガ",
    "ダークライex",
    "セレビィex",
    "アルセウスex",
    "パルキアex",
    "ギラティナex",
    "サーナイト",
    "ピジョットex",
    "ミロカロス",
    "ジバコイル",
    "博士の研究",
    "モンスターボール",
    "サカキ",
    "ナツメ",
    "リーリエ",
    "きずぐすり",
    "スピーダー",
    "ゴツゴツメット",
    "ふしぎなアメ",
    "りゅうせいぐん",
    "サイコキネシス",
  ],
};

export const EXAMPLES_EN = {
  talk: [
    "fire energy acceleration",
    "lightning pokemon that hit the bench",
    "basic with free retreat",
    "supporter that shrinks opponent's hand",
    "attack that gets stronger with coin flips",
    "hp 150+ metal pokemon",
    "mega lucario ex deck",
    "pairs with miraidon ex",
    "popular supporters",
    "heal benched pokemon",
    "search pokemon from deck",
    "supporter that draws cards",
    "card draw ability",
    "shuffle hand into deck and draw",
    "ex with retreat 1 or less",
    "discard opponent's energy",
    "one hit ko basic ex",
    "2 energy 100 damage",
    "weak to fire grass pokemon",
    "basic psychic ex",
    "p energy",
    "darkness stage 2",
    "more energy more damage",
    "flip until tails",
    "hp boost tool",
    "more damage to ex",
    "pairs with venusaur ex",
    "charizard ex partners",
    "pairs with mew ex",
    "pairs with greninja",
    "darkrai ex deck",
    "mega altaria ex deck",
    "vespiquen ex deck",
    "hoopa ex deck",
    "suicune ex deck",
    "lucario deck",
    "milotic ex deck",
    "mega absol ex deck",
    "popular items",
    "popular basic pokemon",
    "popular pokemon",
    "discard from hand",
    "move energy",
    "can't attack next turn",
    "heal attack",
    "returns to hand",
    "evolve faster",
    "stage 1 ex",
    "120 damage",
    "coin flip attack",
    "fire ex",
    "grass ex",
    "metal ex",
    "lightning ex",
    "darkness ex",
    "pikachu ex deck",
    "venusaur ex deck",
    "exeggutor ex deck",
    "gardevoir deck",
    "pairs with dragonite",
    "stop abilities",
    "high hp basic",
    "non-ex pokemon",
    "return pokemon to hand",
    "reduce damage taken",
    "tool that adds hp",
  ],
  basic: [
    "sleep",
    "poison",
    "burn",
    "paralyze",
    "confuse",
    "gust",
    "reduce retreat",
    "damage reduction",
    "prevent damage",
    "item lock",
    "supporter lock",
    "ability lock",
    "bench snipe",
    "self damage",
    "damage counters",
    "stadiums",
    "energy acceleration",
    "switch",
    "hand disruption",
    "energy removal",
    "draw cards",
    "free retreat",
    "tools",
    "damage boost",
    "staples",
    "mega ex",
    "ultra beast",
    "team rocket",
    "ancient pokemon",
    "future pokemon",
    "fossil pokemon",
    "stage 2",
    "basic ex",
    "dragon pokemon",
    "hp 200+",
    "pikachu",
    "charizard",
    "mewtwo ex",
    "greninja",
    "darkrai ex",
    "celebi ex",
    "arceus ex",
    "gardevoir",
    "pidgeot ex",
    "magnezone",
    "professor's research",
    "poke ball",
    "giovanni",
    "sabrina",
    "lillie",
    "potion",
    "x speed",
    "rocky helmet",
    "rare candy",
    "red card",
    "draco meteor",
    "psychic",
  ],
};

const shuffle = <T,>(xs: T[]): T[] => {
  const a = [...xs];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
};

/** 例をランダムに選ぶ（ふだんの言葉の例 talk 個と、カード名・決まった言い方の例 basic 個を混ぜる） */
export function pickExamples(lang: "ja" | "en", talk = 9, basic = 3): string[] {
  const src = lang === "en" ? EXAMPLES_EN : EXAMPLES_JA;
  return shuffle([...shuffle(src.talk).slice(0, talk), ...shuffle(src.basic).slice(0, basic)]);
}
